from .about import about
from .chat import chat
from .index import index
from .scoreboard import scoreboard
from .shelld import shelld
from .unsubscribe import unsubscribe
from .updates import updates
from .sponsors import sponsors
from .jsonfeed import jsonfeed
from core.views import team
from core.views import user
from core.views import problems
