from .index import index
from .scoreboard import scoreboard
from .signup import signup
from .problems import problems
from .profile import profile
from .about import about
from .updates import updates
from .submit_problem import submit_problem
from .chat import chat
from .score import score