# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('value', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('hint', models.TextField()),
                ('flag', models.CharField(max_length=128)),
                ('update_time', models.BooleanField(default=True)),
            ],
        ),
    ]
