# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('school', models.CharField(max_length=128)),
                ('eligible', models.BooleanField(default=True)),
                ('eligible2', models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], null=True)),
                ('address_street', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('address_street_line_2', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('address_zip', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('address_city', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('address_state', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('code', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('score_lastupdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('shell_username', models.CharField(default='', max_length=20)),
                ('shell_password', models.CharField(default='', max_length=50)),
                ('solved', models.ManyToManyField(related_name='solvers', to='api.Problem')),
            ],
        ),
    ]
