# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_correctsubmission_incorrectsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(default='', max_length=40)),
                ('key_generated', models.DateTimeField(default=django.utils.timezone.now)),
                ('eligible', models.BooleanField(default=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Non-binary')], null=True)),
                ('race', models.IntegerField(blank=True, choices=[(1, 'American Indian or Alaskan Native'), (2, 'Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander'), (5, 'White'), (6, 'Two or more races'), (7, 'Other')], null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='api.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
